name: butterfly
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #firebase stuff
  firebase_storage: ^3.1.6
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6

  #bloc for flutter
  flutter_bloc: ^3.2.0

  #annotions
  meta: ^1.1.8

  #allows you to compare objects with the ==, instead of only primitives
  equatable: ^1.2.0

  #work with streams and asynchronous code
  rxdart: ^0.23.0

  #work with path of images
  file_picker: ^1.9.0
  image_picker: ^0.6.7+4

  #fonts
  font_awesome_flutter: ^8.8.1

  #allows you to select date from a drop down bar
  flutter_datetime_picker: ^1.3.8

  #location service
  geolocator: ^5.3.1

  permission_handler: ^3.0.0


  eva_icons_flutter: ^2.0.0
  extended_image: ^0.7.2
  timeago: ^2.0.26
  uuid: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - res/portrait.jpeg
   - res/girl.jpg
   - res/guy.png
   - res/profilephoto.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
